### ISSUE TITLE
M1 MAC ? [CLOSED] [FIXED]

### ISSUE THREAD

**Issue by Snowyodz** [tobspr/RenderPipeline-Samples#7] opened 2021-04-12 11:45 UTC
Does this not support M1 MACBOOKS ? Following error ⬇️ 
`ERROR: Compute shaders not supported! Please update your driver, or get a newer gpu.`

Once opened the trouble shoot page I see no help on mac!

**Comment by rdb** [comment] 2021-04-12 13:01
Duplicate of tobspr/RenderPipeline#108

**Comment by Snowyodz** [comment] 2021-04-13 07:38
> Duplicate of [tobspr/RenderPipeline#108](https://github.com/tobspr/RenderPipeline/issues/108)

Oh thank's it's kinda sad tho

**Closed as completed** 2021-04-13 07:42 UTC
